In [67]:
import pandas as pd

In [68]:
# Data Link = https://www.kaggle.com/datasets/yug201/daily-climate-time-series-data-delhi-india?resource=download

In [69]:
# Loaded the CSV file containing weather data
# Identified a date column with mixed formats (mm/dd/yyyy and dd-mm-yyyy)
# Standardized all date separators to '/'
# Converted the column to proper datetime using pandas with mixed format handling
# Reformatted all dates to a consistent dd/mm/yyyy format
# Saved the cleaned data to a new CSV file without the index

In [70]:
col = [
    "date",
    "temp_max",
    "temp_min",
    "temp_avg",
    "feels_like_max",
    "feels_like_min",
    "feels_like_avg",
    "humidity",
    "precipitation",
    "precipitation_probability",
    "precipitation_coverage",
    "wind_speed",
    "sea_level_pressure",
    "weather_conditions",
    "year",
    "month",
    "day_of_week",
    "day_of_year",
    "year_since_2000",
    "week_of_year",
    "temp_max_humidity",
    "temp_min_humidity",
    "temp_avg_humidity",
    "feels_like_max_humidity",
    "feels_like_min_humidity",
    "feels_like_avg_humidity",
    "temperature_range",
    "heat_index"
]

In [71]:
df=pd.read_csv(r"C:\Users\Asus\Downloads\Weather\kaggel_weather_2013_to_2024.csv",names=col)

In [72]:
df = df.drop(index=0)
df = df.reset_index(drop=True)

In [73]:
df.head()

,date,temp_max,temp_min,temp_avg,feels_like_max,feels_like_min,feels_like_avg,humidity,precipitation,precipitation_probability,...,year_since_2000,week_of_year,temp_max_humidity,temp_min_humidity,temp_avg_humidity,feels_like_max_humidity,feels_like_min_humidity,feels_like_avg_humidity,temperature_range,heat_index
0,4/14/2013,37.7,23.1,28.7,35.4,23.1,28.1,39.7,2,100,...,13,15,1496.69,917.07,1139.39,1405.38,917.07,1115.57,14.6,147.1781178
1,4/15/2013,37.5,21.1,28.6,35.3,21.1,28,41.7,0,0,...,13,16,1563.75,879.87,1192.62,1472.01,879.87,1167.6,16.4,151.7310608
2,4/16/2013,40.1,21.9,31.7,37.5,21.9,30.4,30.7,0,0,...,13,16,1231.07,672.33,973.19,1151.25,672.33,933.28,18.2,118.2111334
3,4/17/2013,36.4,21,29.9,34,21,28.5,27.4,0,0,...,13,16,997.36,575.4,819.26,931.6,575.4,780.9,15.4,113.3203542
4,4/18/2013,37.5,21.7,30.6,35.2,21.7,29.2,23.7,0,0,...,13,16,888.75,514.29,725.22,834.24,514.29,692.04,15.8,101.4070384

In [74]:
df["date"] = pd.to_datetime(
    df["date"],
    format="mixed",
    dayfirst=False
)

In [75]:
df.head()

,date,temp_max,temp_min,temp_avg,feels_like_max,feels_like_min,feels_like_avg,humidity,precipitation,precipitation_probability,...,year_since_2000,week_of_year,temp_max_humidity,temp_min_humidity,temp_avg_humidity,feels_like_max_humidity,feels_like_min_humidity,feels_like_avg_humidity,temperature_range,heat_index
0,2013-04-14,37.7,23.1,28.7,35.4,23.1,28.1,39.7,2,100,...,13,15,1496.69,917.07,1139.39,1405.38,917.07,1115.57,14.6,147.1781178
1,2013-04-15,37.5,21.1,28.6,35.3,21.1,28,41.7,0,0,...,13,16,1563.75,879.87,1192.62,1472.01,879.87,1167.6,16.4,151.7310608
2,2013-04-16,40.1,21.9,31.7,37.5,21.9,30.4,30.7,0,0,...,13,16,1231.07,672.33,973.19,1151.25,672.33,933.28,18.2,118.2111334
3,2013-04-17,36.4,21,29.9,34,21,28.5,27.4,0,0,...,13,16,997.36,575.4,819.26,931.6,575.4,780.9,15.4,113.3203542
4,2013-04-18,37.5,21.7,30.6,35.2,21.7,29.2,23.7,0,0,...,13,16,888.75,514.29,725.22,834.24,514.29,692.04,15.8,101.4070384

In [76]:
df.to_csv(r"C:\Users\Asus\Downloads\Weather\Delhi_Weather_Data.csv", index=False)

In [ ]:
# Import DataSet ON MYSQL

In [77]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Connection details
username = "root"
password = "sourov11@T"    # has '@' so needs encoding
host = "localhost"
port = "3306"
database = "delhi_weather"

# Encode special characters in password
password_encoded = quote_plus(password)

# Correct MySQL engine
engine = create_engine(
    f"mysql+pymysql://{username}:{password_encoded}@{host}:{port}/{database}",
    echo=True
)

# Load DataFrame to MySQL
table_name = "weather"
df.to_sql(table_name, con=engine, if_exists="replace", index=False)

print(f"Data loaded successfully into '{table_name}' table.")

2025-12-28 23:39:57,414 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2025-12-28 23:39:57,420 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,438 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2025-12-28 23:39:57,440 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,443 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2025-12-28 23:39:57,444 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,449 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-12-28 23:39:57,485 INFO sqlalchemy.engine.Engine DESCRIBE `delhi_weather`.`weather`
2025-12-28 23:39:57,486 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,550 INFO sqlalchemy.engine.Engine DESCRIBE `delhi_weather`.`weather`
2025-12-28 23:39:57,551 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,555 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `delhi_weather`
2025-12-28 23:39:57,556 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,567 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `delhi_weather`
2025-12-28 23:39:57,567 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,603 INFO sqlalchemy.engine.Engine SHOW CREATE TABLE `weather`
2025-12-28 23:39:57,605 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-12-28 23:39:57,636 INFO sqlalchemy.engine.Engine
DROP TABLE weather
2025-12-28 23:39:57,637 INFO sqlalchemy.engine.Engine [no key 0.00148s] {}
2025-12-28 23:39:57,711 INFO sqlalchemy.engine.Engine
CREATE TABLE weather (
	date DATETIME,
	temp_max TEXT,
	temp_min TEXT,
	temp_avg TEXT,
	feels_like_max TEXT,
	feels_like_min TEXT,
	feels_like_avg TEXT,
	humidity TEXT,
	precipitation TEXT,
	precipitation_probability TEXT,
	precipitation_coverage TEXT,
	wind_speed TEXT,
	sea_level_pressure TEXT,
	weather_conditions TEXT,
	year TEXT,
	month TEXT,
	day_of_week TEXT,
	day_of_year TEXT,
	year_since_2000 TEXT,
	week_of_year TEXT,
	temp_max_humidity TEXT,
	temp_min_humidity TEXT,
	temp_avg_humidity TEXT,
	feels_like_max_humidity TEXT,
	feels_like_min_humidity TEXT,
	feels_like_avg_humidity TEXT,
	temperature_range TEXT,
	heat_index TEXT
)


2025-12-28 23:39:57,713 INFO sqlalchemy.engine.Engine [no key 0.00126s] {}
2025-12-28 23:39:57,863 INFO sqlalchemy.engine.Engine INSERT INTO weather (date, temp_max, temp_min, temp_avg, feels_like_max, feels_like_min, feels_like_avg, humidity, precipitation, precipitation_probability, precipitation_coverage, wind_speed, sea_level_pressure, weather_conditions, year, month, day_of_week, day_of_year, year_since_2000, week_of_year, temp_max_humidity, temp_min_humidity, temp_avg_humidity, feels_like_max_humidity, feels_like_min_humidity, feels_like_avg_humidity, temperature_range, heat_index) VALUES (%(date)s, %(temp_max)s, %(temp_min)s, %(temp_avg)s, %(feels_like_max)s, %(feels_like_min)s, %(feels_like_avg)s, %(humidity)s, %(precipitation)s, %(precipitation_probability)s, %(precipitation_coverage)s, %(wind_speed)s, %(sea_level_pressure)s, %(weather_conditions)s, %(year)s, %(month)s, %(day_of_week)s, %(day_of_year)s, %(year_since_2000)s, %(week_of_year)s, %(temp_max_humidity)s, %(temp_min_humidity)s, %(temp_avg_humidity)s, %(feels_like_max_humidity)s, %(feels_like_min_humidity)s, %(feels_like_avg_humidity)s, %(temperature_range)s, %(heat_index)s)
2025-12-28 23:39:57,864 INFO sqlalchemy.engine.Engine [generated in 0.06156s] [{'date': datetime.datetime(2013, 4, 14, 0, 0), 'temp_max': '37.7', 'temp_min': '23.1', 'temp_avg': '28.7', 'feels_like_max': '35.4', 'feels_like_min': '23.1', 'feels_like_avg': '28.1', 'humidity': '39.7', 'precipitation': '2', 'precipitation_probability': '100', 'precipitation_coverage': '4.17', 'wind_speed': '22.3', 'sea_level_pressure': '1008.3', 'weather_conditions': 'Rain, Partially cloudy', 'year': '2013', 'month': '4', 'day_of_week': '6', 'day_of_year': '104', 'year_since_2000': '13', 'week_of_year': '15', 'temp_max_humidity': '1496.69', 'temp_min_humidity': '917.07', 'temp_avg_humidity': '1139.39', 'feels_like_max_humidity': '1405.38', 'feels_like_min_humidity': '917.07', 'feels_like_avg_humidity': '1115.57', 'temperature_range': '14.6', 'heat_index': '147.1781178'}, {'date': datetime.datetime(2013, 4, 15, 0, 0), 'temp_max': '37.5', 'temp_min': '21.1', 'temp_avg': '28.6', 'feels_like_max': '35.3', 'feels_like_min': '21.1', 'feels_like_avg': '28', 'humidity': '41.7', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '17.6', 'sea_level_pressure': '1005.1', 'weather_conditions': 'Clear', 'year': '2013', 'month': '4', 'day_of_week': '0', 'day_of_year': '105', 'year_since_2000': '13', 'week_of_year': '16', 'temp_max_humidity': '1563.75', 'temp_min_humidity': '879.87', 'temp_avg_humidity': '1192.62', 'feels_like_max_humidity': '1472.01', 'feels_like_min_humidity': '879.87', 'feels_like_avg_humidity': '1167.6', 'temperature_range': '16.4', 'heat_index': '151.7310608'}, {'date': datetime.datetime(2013, 4, 16, 0, 0), 'temp_max': '40.1', 'temp_min': '21.9', 'temp_avg': '31.7', 'feels_like_max': '37.5', 'feels_like_min': '21.9', 'feels_like_avg': '30.4', 'humidity': '30.7', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '27.7', 'sea_level_pressure': '1001.7', 'weather_conditions': 'Partially cloudy', 'year': '2013', 'month': '4', 'day_of_week': '1', 'day_of_year': '106', 'year_since_2000': '13', 'week_of_year': '16', 'temp_max_humidity': '1231.07', 'temp_min_humidity': '672.33', 'temp_avg_humidity': '973.19', 'feels_like_max_humidity': '1151.25', 'feels_like_min_humidity': '672.33', 'feels_like_avg_humidity': '933.28', 'temperature_range': '18.2', 'heat_index': '118.2111334'}, {'date': datetime.datetime(2013, 4, 17, 0, 0), 'temp_max': '36.4', 'temp_min': '21', 'temp_avg': '29.9', 'feels_like_max': '34', 'feels_like_min': '21', 'feels_like_avg': '28.5', 'humidity': '27.4', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '22.3', 'sea_level_pressure': '1002.5', 'weather_conditions': 'Clear', 'year': '2013', 'month': '4', 'day_of_week': '2', 'day_of_year': '107', 'year_since_2000': '13', 'week_of_year': '16', 'temp_max_humidity': '997.36', 'temp_min_humidity': '575.4', 'temp_avg_humidity': '819.26', 'feels_like_max_humidity': '931.6', 'feels_like_min_humidity': '575.4', 'feels_like_avg_humidity': '780.9', 'temperature_range': '15.4', 'heat_index': '113.3203542'}, {'date': datetime.datetime(2013, 4, 18, 0, 0), 'temp_max': '37.5', 'temp_min': '21.7', 'temp_avg': '30.6', 'feels_like_max': '35.2', 'feels_like_min': '21.7', 'feels_like_avg': '29.2', 'humidity': '23.7', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '12.4', 'sea_level_pressure': '1003.4', 'weather_conditions': 'Clear', 'year': '2013', 'month': '4', 'day_of_week': '3', 'day_of_year': '108', 'year_since_2000': '13', 'week_of_year': '16', 'temp_max_humidity': '888.75', 'temp_min_humidity': '514.29', 'temp_avg_humidity': '725.22', 'feels_like_max_humidity': '834.24', 'feels_like_min_humidity': '514.29', 'feels_like_avg_humidity': '692.04', 'temperature_range': '15.8', 'heat_index': '101.4070384'}, {'date': datetime.datetime(2013, 4, 19, 0, 0), 'temp_max': '37.3', 'temp_min': '21.4', 'temp_avg': '30.3', 'feels_like_max': '35', 'feels_like_min': '21.4', 'feels_like_avg': '28.9', 'humidity': '27.2', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '14.8', 'sea_level_pressure': '1004', 'weather_conditions': 'Clear', 'year': '2013', 'month': '4', 'day_of_week': '4', 'day_of_year': '109', 'year_since_2000': '13', 'week_of_year': '16', 'temp_max_humidity': '1014.56', 'temp_min_humidity': '582.08', 'temp_avg_humidity': '824.16', 'feels_like_max_humidity': '952', 'feels_like_min_humidity': '582.08', 'feels_like_avg_humidity': '786.08', 'temperature_range': '15.9', 'heat_index': '111.9869377'}, {'date': datetime.datetime(2013, 4, 20, 0, 0), 'temp_max': '37.7', 'temp_min': '22.2', 'temp_avg': '30.6', 'feels_like_max': '36', 'feels_like_min': '22.2', 'feels_like_avg': '29.4', 'humidity': '27.8', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '16', 'sea_level_pressure': '1003.9', 'weather_conditions': 'Partially cloudy', 'year': '2013', 'month': '4', 'day_of_week': '5', 'day_of_year': '110', 'year_since_2000': '13', 'week_of_year': '16', 'temp_max_humidity': '1048.06', 'temp_min_humidity': '617.16', 'temp_avg_humidity': '850.68', 'feels_like_max_humidity': '1000.8', 'feels_like_min_humidity': '617.16', 'feels_like_avg_humidity': '817.32', 'temperature_range': '15.5', 'heat_index': '113.056248'}, {'date': datetime.datetime(2013, 4, 21, 0, 0), 'temp_max': '37', 'temp_min': '23.9', 'temp_avg': '28.4', 'feels_like_max': '35.4', 'feels_like_min': '23.9', 'feels_like_avg': '28.1', 'humidity': '39.5', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '27.7', 'sea_level_pressure': '1007.2', 'weather_conditions': 'Partially cloudy', 'year': '2013', 'month': '4', 'day_of_week': '6', 'day_of_year': '111', 'year_since_2000': '13', 'week_of_year': '16', 'temp_max_humidity': '1461.5', 'temp_min_humidity': '944.05', 'temp_avg_humidity': '1121.8', 'feels_like_max_humidity': '1398.3', 'feels_like_min_humidity': '944.05', 'feels_like_avg_humidity': '1109.95', 'temperature_range': '13.1', 'heat_index': '147.7320704'}  ... displaying 10 of 3557 total bound parameter sets ...  {'date': datetime.datetime(2024, 11, 29, 0, 0), 'temp_max': '25', 'temp_min': '10.6', 'temp_avg': '18', 'feels_like_max': '25', 'feels_like_min': '10.6', 'feels_like_avg': '18', 'humidity': '60', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '7.6', 'sea_level_pressure': '1017.4', 'weather_conditions': 'Clear', 'year': '2024', 'month': '11', 'day_of_week': '4', 'day_of_year': '334', 'year_since_2000': '24', 'week_of_year': '48', 'temp_max_humidity': '1500', 'temp_min_humidity': '636', 'temp_avg_humidity': '1080', 'feels_like_max_humidity': '1500', 'feels_like_min_humidity': '636', 'feels_like_avg_humidity': '1080', 'temperature_range': '14.4', 'heat_index': '237.6383442'}, {'date': datetime.datetime(2024, 11, 30, 0, 0), 'temp_max': '25', 'temp_min': '11', 'temp_avg': '18', 'feels_like_max': '25', 'feels_like_min': '11', 'feels_like_avg': '18', 'humidity': '63.3', 'precipitation': '0', 'precipitation_probability': '0', 'precipitation_coverage': '0', 'wind_speed': '11.2', 'sea_level_pressure': '1015.5', 'weather_conditions': 'Clear', 'year': '2024', 'month': '11', 'day_of_week': '5', 'day_of_year': '335', 'year_since_2000': '24', 'week_of_year': '48', 'temp_max_humidity': '1582.5', 'temp_min_humidity': '696.3', 'temp_avg_humidity': '1139.4', 'feels_like_max_humidity': '1582.5', 'feels_like_min_humidity': '696.3', 'feels_like_avg_humidity': '1139.4', 'temperature_range': '14', 'heat_index': '242.7538009'}]
2025-12-28 23:39:58,203 INFO sqlalchemy.engine.Engine COMMIT
Data loaded successfully into 'weather' table.